### ISSUE TITLE
how to resolve this

### ISSUE THREAD

**Issue by abharna** [chaquo/chaquopy-hello#15]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.checkhello, PID: 12937
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.checkhello/com.example.checkhello.MainActivity}: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'myscript'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'myscript'
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:973)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule(chaquopy_java.pyx:153)
        at com.chaquo.python.Python.getModule(Native Method)
        at com.example.checkhello.MainActivity.onCreate(MainActivity.java:22)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by mhsmith** [comment]
Do you have a file called myscript.py in app/src/main/python?

**Comment by abharna** [comment]
ss,I have the file in this location C:\Users\user\AndroidStudioProjects\checkhello\app\src\main\python\myscript.py

**Comment by mhsmith** [comment]
Then I can't guess what the problem might be. Have you changed any of the [`sourceSets`](https://chaquo.com/chaquopy/doc/current/android.html#source-code) settings?

Otherwise, can you upload the project to GitHub, or at least a simplified version which shows the same problem?

**Comment by abharna** [comment]
apply plugin: 'com.android.application'
apply plugin: 'com.chaquo.python'        // Add this line


android {
    compileSdkVersion 29
    buildToolsVersion "29.0.3"

    defaultConfig {
        applicationId "com.example.checkhello"
        sourceSets {
            main {
                python {
                    srcDirs = ["replacement/dir"]
                    srcDir "additional/dir"
                }
            }
        }
//        python {
//            pip {
//                install "six"
//                install "scipy==1.0.1"
//                install "LocalPackage-1.2.3-py2.py3-none-any.whl"
//                install "-r", "requirements.txt"
//            }
//        }
//        pip {
//            options "--extra-index-url", "https://example.com/private/repository"
//            install "PrivatePackage==1.2.3"
//        }

        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        python {
            buildPython "C:/Python36/python.exe"
            buildPython "py -3.7"
        }

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}

**Comment by abharna** [comment]
i include the sourceset also in the above coding

**Comment by mhsmith** [comment]
As the [documentation](https://chaquo.com/chaquopy/doc/current/android.html#source-code) says, the `sourceSets` block is used "to add or change source directories". I don't think you have any need to do that, so you should just remove the block.

**Comment by abharna** [comment]
without sourceset also it show the same error as
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.checkhello, PID: 16676
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.checkhello/com.example.checkhello.MainActivity}: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'C:/Users/user/AndroidStudioProjects/checkhello/app/src/main/python/myscript'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'C:/Users/user/AndroidStudioProjects/checkhello/app/src/main/python/myscript'
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:973)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib._bootstrap._call_with_frames_removed(<frozen importlib._bootstrap>:219)
        at <python>.importlib._bootstrap._find_and_load_unlocked(<frozen importlib._bootstrap>:961)
        at <python>.importlib._bootstrap._find_and_load(<frozen importlib._bootstrap>:991)
        at <python>.importlib._bootstrap._gcd_import(<frozen importlib._bootstrap>:1014)
        at <python>.importlib.import_module(__init__.py:127)
        at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule(chaquopy_java.pyx:153)
        at com.chaquo.python.Python.getModule(Native Method)
        at com.example.checkhello.MainActivity.onCreate(MainActivity.java:22)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by mhsmith** [comment]
Don't pass the full path to `getModule`, just pass the module name, "myscript".

**Comment by mhsmith** [comment]
If you still have problems with getModule, please reopen and give details. 

If you have any other problems, please create a separate issue in [the main project](https://github.com/chaquo/chaquopy/issues).
