### ISSUE TITLE
How to import requests ?  

### ISSUE THREAD

**Issue by hushanhsiang** [chaquo/chaquopy-hello#3]
I add one line as below but got error(No module named 'requests'):
from requests import request

The Error message:
`01-11 13:20:54.402 3193-3193/com.chaquo.python.hello E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.chaquo.python.hello, PID: 3193
                                                                       java.lang.ExceptionInInitializerError
                                                                           at java.lang.Class.newInstance(Native Method)
                                                                           at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2335)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
                                                                           at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5451)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                        Caused by: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'requests'
                                                                           at <python>.java.chaquopy.import_override (.c:59641)(java\import.pxi:18)
                                                                           at <python>.reraise(/data/user/0/com.chaquo.python.hello/files/chaquopy/chaquopy.zip/java/_vendor/six.py:686)
                                                                           at <python>.java.chaquopy.import_override (.c:60681)(java\import.pxi:53)
                                                                           at <python>.<module>(/android_asset/chaquopy/app.zip/hello.py:6)
                                                                           at <python>.load_module_impl(/data/user/0/com.chaquo.python.hello/files/chaquopy/chaquopy.zip/java/android/importer.py:155)
                                                                           at <python>.load_module(/data/user/0/com.chaquo.python.hello/files/chaquopy/chaquopy.zip/java/android/importer.py:91)
                                                                           at <python>._load_backward_compatible(<frozen importlib._bootstrap>:626)
                                                                           at <python>._load_unlocked(<frozen importlib._bootstrap>:656)
                                                                           at <python>._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
                                                                           at <python>._find_and_load(<frozen importlib._bootstrap>:971)
                                                                           at <python>._gcd_import(<frozen importlib._bootstrap>:994)
                                                                           at <python>.import_module(/data/user/0/com.chaquo.python.hello/files/chaquopy/stdlib.zip/importlib/__init__.py:126)
                                                                           at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule (.c:2790)(chaquopy_java.pyx:128)
                                                                           at com.chaquo.python.Python.getModule(Native Method)
                                                                           at hello.MainActivity.<clinit>(MainActivity.java:13)
                                                                           at java.lang.Class.newInstance(Native Method) 
                                                                           at android.app.Instrumentation.newActivity(Instrumentation.java:1068) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2335) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
                                                                           at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5451) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
`

**Comment by mhsmith** [comment]
requests is not part of the standard library. You'll have to install it [using pip](https://chaquo.com/chaquopy/doc/current/android.html#requirements).

**Comment by hushanhsiang** [comment]
I tried below before I raised this issue. 

            pip { 
                requests
            }
        }

The error message:
下午 08:01	Gradle sync failed: Could not get unknown property 'requests' for object of type com.chaquo.python.PythonExtension.
					Consult IDE log for more details (Help | Show Log) (2s 164ms)

**Comment by mhsmith** [comment]
The full error will be in the "Gradle console" window. If you can't understand it, please post it along with your complete build.gradle file

**Comment by hushanhsiang** [comment]
After I reload chaquopy-helo-master 
1. put pip { install "request"}  in python{} of Gradle
2. write my code in hello.py
No errors happen.... Something wrong.... 
But my code has errors while try: requests.request which is running without problem in PC mode.

**Comment by hushanhsiang** [comment]
The part of code as below
`        body ={'url':'https://pbs.twimg.com/media/C22VR8qUsAAlQev.jpg'}
        try:
            # Execute the REST API call and get the response.
            response = request('POST', uri_base + '/face/v1.0/detect', json=body, data=None, headers=headers, params=params)

            #print ('Response:')
            self.findViewById(R.id.tvx).setText("Response")
            parsed = loads(response.text)
            print (dumps(parsed, sort_keys=True, indent=2))

        except Exception as e:
            #print('Error:')
            self.findViewById(R.id.tvx).setText("Error")
            self.findViewById(R.id.tvx).setText(str(e))
            #print(e)`
The error message of "e":
Could not find suitable TLS CA certificate bundle, invalid path: /android_asset/chaquopy/requirements.zip/certifi/cacert.pem

**Comment by mhsmith** [comment]
I'm afraid there's no current workaround for this because our Python builds don't include TLS support. We'll fix this in the next few days.

**Comment by hushanhsiang** [comment]
My PC installed conda(Anaconda) to handle python and its packages, maybe this error comes from conda which some topics on the internet.

**Comment by mhsmith** [comment]
No, don't waste any time on that, the copy of Python built into your APK is independent of what you have installed on the build machine.

**Comment by hushanhsiang** [comment]
Everything seems fine now if you update your new code with TLS then I will create my python project with Chaquopy.

**Comment by mhsmith** [comment]
Fixed in Chaquopy 1.3.0.

**Comment by mhsmith** [comment]
For any other errors involving an "android_asset" path, see https://chaquo.com/chaquopy/doc/current/android.html#resource-files.

**Comment by hushanhsiang** [comment]
"requests" is running but not correct, should I raise another issue?
The almost same code to run in PC (Windows) side is OK, but with chaquopy is not correct!!
The error message as below:
`01-17 11:14:57.834 578-578/com.chaquo.python.hello E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.chaquo.python.hello, PID: 578
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chaquo.python.hello/hello.MainActivity}: com.chaquo.python.PyException: ConnectionError: HTTPSConnectionPool(host='westcentralus.api.cognitive.microsoft.com', port=443): Max retries exceeded with url: /face/v1.0/detect?returnFaceId=true&returnFaceLandmarks=false&returnFaceAttributes=age%2Cgender%2CheadPose%2Csmile%2CfacialHair%2Cglasses%2Cemotion%2Chair%2Cmakeup%2Cocclusion%2Caccessories%2Cblur%2Cexposure%2Cnoise (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xdfdd9d50>: Failed to establish a new connection: [Errno 7] No address associated with hostname',))
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5451)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                      Caused by: com.chaquo.python.PyException: ConnectionError: HTTPSConnectionPool(host='westcentralus.api.cognitive.microsoft.com', port=443): Max retries exceeded with url: /face/v1.0/detect?returnFaceId=true&returnFaceLandmarks=false&returnFaceAttributes=age%2Cgender%2CheadPose%2Csmile%2CfacialHair%2Cglasses%2Cemotion%2Chair%2Cmakeup%2Cocclusion%2Caccessories%2Cblur%2Cexposure%2Cnoise (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xdfdd9d50>: Failed to establish a new connection: [Errno 7] No address associated with hostname',))
                                                                         at <python>.send(/android_asset/chaquopy/requirements.zip/requests/adapters.py:508)
                                                                         at <python>.send(/android_asset/chaquopy/requirements.zip/requests/sessions.py:618)
                                                                         at <python>.request(/android_asset/chaquopy/requirements.zip/requests/sessions.py:508)
                                                                         at <python>.request(/android_asset/chaquopy/requirements.zip/requests/api.py:58)
                                                                         at <python>.onCreate(/android_asset/chaquopy/app.zip/hello.py:55)
                                                                         at <python>.chaquopy_java.call (.c:5092)(chaquopy_java.pyx:256)
                                                                         at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows (.c:4610)(chaquopy_java.pyx:228)
                                                                         at com.chaquo.python.PyObject.callAttrThrows(Native Method)
                                                                         at com.chaquo.python.PyObject._chaquopyCall(PyObject.java:150)
                                                                         at hello.MainActivity.onCreate(MainActivity.java:24)
                                                                         at android.app.Activity.performCreate(Activity.java:6323)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:148) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5451) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
01-17 11:14:59.572 578-578/com.chaquo.python.hello I/Process: Sending signal. PID: 578 SIG: 9
`

**Comment by mhsmith** [comment]
https://stackoverflow.com/questions/6355498/unable-to-resolve-host-url-here-no-address-associated-with-hostname/24484213

This is a common Android issue which has nothing to do with Chaquopy. Please search more carefully before asking for help here.

**Comment by hushanhsiang** [comment]
Ok, it's working well now.
Thank you for help.
