### ISSUE TITLE
How to make python's project as chaquopy-hello?

### ISSUE THREAD

**Issue by hushanhsiang** [chaquo/chaquopy-hello#5]
Do you have the document about how to make chaquopy-hello?

I'd like to make my own projects and can start from python code as chaquopy-hello, I followed most items of Android of Chaquopy 1.2 document with removed MainActivity.java and copy hello.py of chaquopy-hello but got error message :"Default Activity not found"..

May I have you help to make a python start-up Android project as chaquopy-hello from "new project" of Android Studio?

**Comment by mhsmith** [comment]
The minimal set of changes you need are shown in this commit: https://github.com/chaquo/chaquopy-hello/commit/391d9ca15398cb2609d2f1e614ce752690a2d61e

**Comment by hushanhsiang** [comment]
If I initiated a new project by below setting: 
1.Application name: hello
2. Company domain :python.chaquopy.com
The picture:
https://images2.imgbox.com/12/0a/WlK7g5V8_o.png
Follow all of the [391d9ca](<https://github.com/chaquo/chaquopy-hello/commit/391d9ca15398cb2609d2f1e614ce752690a2d61e>)  "391d9ca" then this "hello" project will be fine without any problem.

I'd like to create my own new project and changed "Application name" to "test1" and "Company domain" to "python.oscarhu.com". And also change:
1. hello.py to test1.py
2. staticProxy "test1" in Grandle(module)
3. "from com.chaquo.python.test1 import R" in test1.py
4. <activity android:name="test1.MainActivity"> in AndroidManifest.xml
But got probelm as below: 
`01-14 14:56:37.582 8268-8268/com.oscarhu.python.test1 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.oscarhu.python.test1, PID: 8268
                                                                        java.lang.ExceptionInInitializerError
                                                                            at java.lang.Class.newInstance(Native Method)
                                                                            at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2335)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5451)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                         Caused by: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'com'
                                                                            at <python>.java.chaquopy.import_override (.c:59641)(java\import.pxi:18)
                                                                            at <python>.reraise(/data/user/0/com.oscarhu.python.test1/files/chaquopy/chaquopy.zip/java/_vendor/six.py:686)
                                                                            at <python>.java.chaquopy.import_override (.c:60681)(java\import.pxi:53)
                                                                            at <python>.<module>(/android_asset/chaquopy/app.zip/test1.py:3)
                                                                            at <python>.load_module_impl(/data/user/0/com.oscarhu.python.test1/files/chaquopy/chaquopy.zip/java/android/importer.py:155)
                                                                            at <python>.load_module(/data/user/0/com.oscarhu.python.test1/files/chaquopy/chaquopy.zip/java/android/importer.py:91)
                                                                            at <python>._load_backward_compatible(<frozen importlib._bootstrap>:626)
                                                                            at <python>._load_unlocked(<frozen importlib._bootstrap>:656)
                                                                            at <python>._find_and_load_unlocked(<frozen importlib._bootstrap>:955)
                                                                            at <python>._find_and_load(<frozen importlib._bootstrap>:971)
                                                                            at <python>._gcd_import(<frozen importlib._bootstrap>:994)
                                                                            at <python>.import_module(/data/user/0/com.oscarhu.python.test1/files/chaquopy/stdlib.zip/importlib/__init__.py:126)
                                                                            at <python>.chaquopy_java.Java_com_chaquo_python_Python_getModule (.c:2790)(chaquopy_java.pyx:128)
                                                                            at com.chaquo.python.Python.getModule(Native Method)
                                                                            at test1.MainActivity.<clinit>(MainActivity.java:13)
                                                                            at java.lang.Class.newInstance(Native Method) 
                                                                            at android.app.Instrumentation.newActivity(Instrumentation.java:1068) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2335) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5451) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
01-14 14:56:39.942 8268-8268/com.oscarhu.python.test1 I/Process: Sending signal. PID: 8268 SIG: 9
`

**Comment by hushanhsiang** [comment]
Everything is fine if follow 391d9ca but need to modify some if I'd like to initiate my own projects.
Thank you very much.
